version: '3.3'

services:
  web:
    container_name: challenge-devops1-web
    build:     
        context: .
        dockerfile: Dockerfile-django
    ports:
      - 8000:8000/tcp
    depends_on:
      - "db"
  db:
    container_name: challenge-devops1-db
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_TCP_PORT=3307
      - MYSQLX_TCP_PORT=33070
    ports:
      - 3307:3307/tcp     
      - 33070:33070/tcp
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb:

