version: '3.3'

services:

  web:
    container_name: challenge-devops1-web
    build:     
        context: .
        dockerfile: Dockerfile-django
    ports:
      - 8000:8000/tcp
    network_mode: host
    depends_on:
      - "db"
  db:
    container_name: challenge-devops1-db
    image: "mysql:latest"
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_USER=root@127.0.0.1
      - MYSQL_PASSWORD=supersecret
      - MYSQL_TCP_PORT=3306
    ports:
      - 3306:3306/tcp     
    network_mode: host

