# syntax=docker/dockerfile:1
FROM python:3.9-buster
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY drf /drf/
WORKDIR /drf/
RUN pip install --upgrade pip 
RUN pip install -r requirements.txt
RUN pip install pymysql
RUN pip install mysqlclient
RUN apt get update
CMD ["python3", "manage.py", "migrate"]
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
EXPOSE 8000
